ad2210_monitoring:
    application_name: '%env(MONITORING_APPLICATION_NAME)%'
    environment: '%kernel.environment%'
    health:
        token: '%env(MONITORING_HEALTH_TOKEN)%'
    metrics:
        token: '%env(MONITORING_METRICS_TOKEN)%'
